import {STRINGS} from './strings';

export const steps = {
  [STRINGS.COMPANY_DETAILS_KEY]: STRINGS.COMPANY_DETAILS_VALUE,
  [STRINGS.CONTACT_PERSON_DETAILS_KEY]: STRINGS.CONTACT_PERSON_DETAILS_VALUE,
  //   [STRINGS.DOCUMENT_VARIFICATION_KEY]: STRINGS.DOCUMENT_VARIFICATION_VALUE,
  [STRINGS.PACKAGE_DETAILS_KEY]: STRINGS.PACKAGE_DETAILS_VALUE,
};
